### ISSUE TITLE
Unable to run on Synology

### ISSUE THREAD

**Issue by OrangeChu** [haq/microsoft-rewards-bot#18]
When I ran the `Docker run -- rm - it -- shm size 4g -- v/volume1/Docker/microsoft/accounts. json:/app/accounts. json ghcr.io/haq/microsoft warnings bot` script in the running environment of Synology, the following error occurred:

```
Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "/app/src/__init__.py", line 1, in <module>
    from .browser import Browser
  File "/app/src/browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 12, in <module>
    from seleniumwire.inspect import InspectRequestsMixin
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/inspect.py", line 7, in <module>
    from seleniumwire import har
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'
```

Did I miss anything?

**Comment by haq** [comment]
https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/455

Looks to be an upstream issue. 
The project might have been abandoned., I will look for an alternative.
